package com.zhongyang.java.vo;

import java.util.Date;

public class UserInfoVo  {
	
    private String id;

    private String channel;

    private String clientcode;

    private String email;

    private Boolean enabled;

    private Boolean enterprise;

    private String groupid;

    private String idnumber;

    private Date lastlogindate;
    private String strLastLoginDate;
	private String lastmodifiedby;

    private String loginname;

    private String mobile;

    private String name;

    private Boolean needchangepassword;

    private String passphrase;

    private Boolean referralrewarded;

    private Date registerdate;

    private Boolean registryrewarded;

    private String salt;

    private String source;

    private String referralId;

    private String referralRealm;

    private String priv;

    private Boolean type;

    private Boolean idauthenticated;

    private Boolean emailauthenticated;

    private Boolean mobileauthenticated;

    private String paymentpassphrase;

    private String paymentsalt;
    
    private Boolean cardauthenticated;
    private Boolean defaultaccount;
    
    private int loginCounter;
    /**
     * 快捷支付协议
     * ZKJP0700
     */
    private boolean instant;

    /*
     * 无密投资协议:ZTBB0G00
     */
    private boolean invest;

    public boolean isInstant() {
		return instant;
	}

	public void setInstant(boolean instant) {
		this.instant = instant;
	}

	public boolean isInvest() {
		return invest;
	}

	public void setInvest(boolean invest) {
		this.invest = invest;
	}

	public boolean isRepay() {
		return repay;
	}

	public void setRepay(boolean repay) {
		this.repay = repay;
	}

	public boolean isDebit() {
		return debit;
	}

	public void setDebit(boolean debit) {
		this.debit = debit;
	}

	/*
     * 无密还款协议:ZHKB0H01
     */
    private boolean repay;

    /*
     * 借记卡快捷协议:ZKJP0700
     */
    private boolean debit;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_FUND_ACCOUNT.TIMERECORDED
     *
     * @mbggenerated
     */
    private Date timerecorded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 是否已通过验证， 默认1为通过验证,所属表字段为TB_FUND_ACCOUNT.VALID
     *
     * @mbggenerated
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 银行卡号,所属表字段为TB_FUND_ACCOUNT.ACCOUNT
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 银行,所属表字段为TB_FUND_ACCOUNT.BANK
     *
     * @mbggenerated
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 银行电话,所属表字段为TB_FUND_ACCOUNT.BANKMOBILE
     *
     * @mbggenerated
     */
    private String bankmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_FUND_ACCOUNT.BRANCH
     *
     * @mbggenerated
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 城市,所属表字段为TB_FUND_ACCOUNT.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 位置,所属表字段为TB_FUND_ACCOUNT.LOCATION
     *
     * @mbggenerated
     */
    private String location;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 省份,所属表字段为TB_FUND_ACCOUNT.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户ID,所属表字段为TB_FUND_ACCOUNT.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_FUND_ACCOUNT.EXPRESSACCOUNT
     *
     * @mbggenerated
     */
    private Boolean expressaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_FUND_ACCOUNT.DELETED
     *
     * @mbggenerated
     */
    private Boolean deleted;
    
    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getClientcode() {
		return clientcode;
	}

	public void setClientcode(String clientcode) {
		this.clientcode = clientcode;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Boolean getEnterprise() {
		return enterprise;
	}

	public void setEnterprise(Boolean enterprise) {
		this.enterprise = enterprise;
	}

	public String getGroupid() {
		return groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getIdnumber() {
		return idnumber;
	}

	public void setIdnumber(String idnumber) {
		this.idnumber = idnumber;
	}

	public Date getLastlogindate() {
		return lastlogindate;
	}

	public void setLastlogindate(Date lastlogindate) {
		this.lastlogindate = lastlogindate;
	}

	public String getStrLastLoginDate() {
		return strLastLoginDate;
	}

	public void setStrLastLoginDate(String strLastLoginDate) {
		this.strLastLoginDate = strLastLoginDate;
	}

	public String getLastmodifiedby() {
		return lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getNeedchangepassword() {
		return needchangepassword;
	}

	public void setNeedchangepassword(Boolean needchangepassword) {
		this.needchangepassword = needchangepassword;
	}

	public String getPassphrase() {
		return passphrase;
	}

	public void setPassphrase(String passphrase) {
		this.passphrase = passphrase;
	}

	public Boolean getReferralrewarded() {
		return referralrewarded;
	}

	public void setReferralrewarded(Boolean referralrewarded) {
		this.referralrewarded = referralrewarded;
	}

	public Date getRegisterdate() {
		return registerdate;
	}

	public void setRegisterdate(Date registerdate) {
		this.registerdate = registerdate;
	}

	public Boolean getRegistryrewarded() {
		return registryrewarded;
	}

	public void setRegistryrewarded(Boolean registryrewarded) {
		this.registryrewarded = registryrewarded;
	}

	public String getSalt() {
		return salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getReferralId() {
		return referralId;
	}

	public void setReferralId(String referralId) {
		this.referralId = referralId;
	}

	public String getReferralRealm() {
		return referralRealm;
	}

	public void setReferralRealm(String referralRealm) {
		this.referralRealm = referralRealm;
	}

	public String getPriv() {
		return priv;
	}

	public void setPriv(String priv) {
		this.priv = priv;
	}

	public Boolean getType() {
		return type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	public Boolean getIdauthenticated() {
		return idauthenticated;
	}

	public void setIdauthenticated(Boolean idauthenticated) {
		this.idauthenticated = idauthenticated;
	}

	public Boolean getEmailauthenticated() {
		return emailauthenticated;
	}

	public void setEmailauthenticated(Boolean emailauthenticated) {
		this.emailauthenticated = emailauthenticated;
	}

	public Boolean getMobileauthenticated() {
		return mobileauthenticated;
	}

	public void setMobileauthenticated(Boolean mobileauthenticated) {
		this.mobileauthenticated = mobileauthenticated;
	}

	public String getPaymentpassphrase() {
		return paymentpassphrase;
	}

	public void setPaymentpassphrase(String paymentpassphrase) {
		this.paymentpassphrase = paymentpassphrase;
	}

	public String getPaymentsalt() {
		return paymentsalt;
	}

	public void setPaymentsalt(String paymentsalt) {
		this.paymentsalt = paymentsalt;
	}

	public Boolean getCardauthenticated() {
		return cardauthenticated;
	}

	public void setCardauthenticated(Boolean cardauthenticated) {
		this.cardauthenticated = cardauthenticated;
	}



    public String getBank() {
		return bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public Boolean getDefaultaccount() {
		return defaultaccount;
	}

	public void setDefaultaccount(Boolean defaultaccount) {
		this.defaultaccount = defaultaccount;
	}

	public Date getTimerecorded() {
		return timerecorded;
	}

	public void setTimerecorded(Date timerecorded) {
		this.timerecorded = timerecorded;
	}

	public Boolean getValid() {
		return valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getBankmobile() {
		return bankmobile;
	}

	public void setBankmobile(String bankmobile) {
		this.bankmobile = bankmobile;
	}

	public String getBranch() {
		return branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Boolean getExpressaccount() {
		return expressaccount;
	}

	public void setExpressaccount(Boolean expressaccount) {
		this.expressaccount = expressaccount;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public int getLoginCounter() {
		return loginCounter;
	}

	public void setLoginCounter(int loginCounter) {
		this.loginCounter = loginCounter;
	}

    

}