package com.zhongyang.java.pojo;

import java.util.Date;

public class InvestContractInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_INVEST_CONTRACT_INFO.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_INVEST_CONTRACT_INFO.CONTRACTNO
     *
     * @mbggenerated
     */
    private String contractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_INVEST_CONTRACT_INFO.PATH
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_INVEST_CONTRACT_INFO.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_INVEST_CONTRACT_INFO.EXPIRED_DATE
     *
     * @mbggenerated
     */
    private Date expiredDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_INVEST_CONTRACT_INFO.ISDEL
     *
     * @mbggenerated
     */
    private Boolean isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_INVEST_CONTRACT_INFO.INVESTID
     *
     * @mbggenerated
     */
    private String investid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVEST_CONTRACT_INFO.ID
     *
     * @return the value of TB_INVEST_CONTRACT_INFO.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVEST_CONTRACT_INFO.ID
     *
     * @param id the value for TB_INVEST_CONTRACT_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVEST_CONTRACT_INFO.CONTRACTNO
     *
     * @return the value of TB_INVEST_CONTRACT_INFO.CONTRACTNO
     *
     * @mbggenerated
     */
    public String getContractno() {
        return contractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVEST_CONTRACT_INFO.CONTRACTNO
     *
     * @param contractno the value for TB_INVEST_CONTRACT_INFO.CONTRACTNO
     *
     * @mbggenerated
     */
    public void setContractno(String contractno) {
        this.contractno = contractno == null ? null : contractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVEST_CONTRACT_INFO.PATH
     *
     * @return the value of TB_INVEST_CONTRACT_INFO.PATH
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVEST_CONTRACT_INFO.PATH
     *
     * @param path the value for TB_INVEST_CONTRACT_INFO.PATH
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVEST_CONTRACT_INFO.CREATE_DATE
     *
     * @return the value of TB_INVEST_CONTRACT_INFO.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVEST_CONTRACT_INFO.CREATE_DATE
     *
     * @param createDate the value for TB_INVEST_CONTRACT_INFO.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVEST_CONTRACT_INFO.EXPIRED_DATE
     *
     * @return the value of TB_INVEST_CONTRACT_INFO.EXPIRED_DATE
     *
     * @mbggenerated
     */
    public Date getExpiredDate() {
        return expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVEST_CONTRACT_INFO.EXPIRED_DATE
     *
     * @param expiredDate the value for TB_INVEST_CONTRACT_INFO.EXPIRED_DATE
     *
     * @mbggenerated
     */
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVEST_CONTRACT_INFO.ISDEL
     *
     * @return the value of TB_INVEST_CONTRACT_INFO.ISDEL
     *
     * @mbggenerated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVEST_CONTRACT_INFO.ISDEL
     *
     * @param isdel the value for TB_INVEST_CONTRACT_INFO.ISDEL
     *
     * @mbggenerated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVEST_CONTRACT_INFO.INVESTID
     *
     * @return the value of TB_INVEST_CONTRACT_INFO.INVESTID
     *
     * @mbggenerated
     */
    public String getInvestid() {
        return investid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVEST_CONTRACT_INFO.INVESTID
     *
     * @param investid the value for TB_INVEST_CONTRACT_INFO.INVESTID
     *
     * @mbggenerated
     */
    public void setInvestid(String investid) {
        this.investid = investid == null ? null : investid.trim();
    }
}