package com.zhongyang.java.dao;

import com.zhongyang.java.pojo.InvestContractInfo;

public interface InvestContractInfoMapper {
	
	InvestContractInfo selectByInvestId(String investId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INVEST_CONTRACT_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INVEST_CONTRACT_INFO
     *
     * @mbggenerated
     */
    int insert(InvestContractInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INVEST_CONTRACT_INFO
     *
     * @mbggenerated
     */
    int insertSelective(InvestContractInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INVEST_CONTRACT_INFO
     *
     * @mbggenerated
     */
    InvestContractInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INVEST_CONTRACT_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InvestContractInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INVEST_CONTRACT_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InvestContractInfo record);
}